# Generated by Django 4.1.5 on 2023-02-10 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(db_index=True, max_length=15, unique=True)),
                ('postal_code', models.CharField(max_length=30)),
                ('fax', models.CharField(max_length=20)),
                ('email', models.CharField(db_index=True, max_length=200, unique=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.address')),
            ],
        ),
    ]
