# Generated by Django 4.1.5 on 2023-02-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(blank=True, max_length=50, null=True)),
                ('line2', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, default='Assiut', max_length=30)),
                ('governorate', models.CharField(blank=True, default='Assiut', max_length=30, null=True)),
                ('zipCode', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
