# Generated by Django 4.1.5 on 2023-02-12 11:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('order_tracking_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('order_taxes', models.FloatField(default=50)),
                ('order_state', models.CharField(choices=[('Arrived', 'Arrived'), ('Not Arrived', 'Not Arrived')], default='Not Arrived', max_length=12)),
                ('order_amount', models.PositiveIntegerField(default=1)),
                ('estimated_delivery_time', models.DateField(default=datetime.datetime.now)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.address')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cart.cart')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
