# Generated by Django 4.1.5 on 2023-02-07 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.address'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
