# Generated by Django 4.1.5 on 2023-02-15 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_description_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.imagemodel'),
        ),
    ]
