# Generated by Django 4.1.5 on 2023-02-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customer_user_name_alter_customer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='governorate',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='zipCode',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Governorate',
        ),
    ]
