# Generated by Django 4.1.5 on 2023-02-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_address_governorate_address_zipcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default='Assiut', max_length=30),
        ),
        migrations.AlterField(
            model_name='address',
            name='governorate',
            field=models.CharField(default='Assiut', max_length=30, null=True),
        ),
    ]
