# Generated by Django 4.1.5 on 2023-02-10 13:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('order_tracking_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('order_taxes', models.FloatField(default=50)),
                ('order_state', models.CharField(choices=[('Arrived', 'Arrived'), ('Not Arrived', 'Not Arrived')], default='ARRIVED', max_length=12)),
                ('order_amount', models.PositiveIntegerField(default=1)),
                ('estimated_delivery_time', models.DateField(default=datetime.datetime.now)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.address')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cart.cart')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
